#!/bin/bash

echo ""
echo "🗺️  World Cup 2026 Map - Build System"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📦 OPCIONES DE BUILD:"
echo ""
echo "  1. npm run build:vanilla  → HTML puro sin React ⭐ NUEVO"
echo "     └─ Output: dist-vanilla/"
echo "     └─ HTML completo (no <div id=\"root\">)"
echo "     └─ JavaScript vanilla + Google Maps API"
echo "     └─ ✅ RECOMENDADO para Directus/edición"
echo ""
echo "  2. npm run build:static   → Archivos separados (con React)"
echo "     └─ Output: dist-static/"
echo "     └─ HTML limpio y editable"
echo "     └─ ✅ Para desarrollo"
echo ""
echo "  3. npm run build:inline   → Todo en un archivo HTML"
echo "     └─ Output: dist-inline/"
echo "     └─ 100% portable y standalone"
echo "     └─ ✅ Para compartir/demos"
echo ""
echo "  4. npm run build:html     → HTML ultra comprimido"
echo "     └─ Output: dist-html/"
echo "     └─ Minificado y optimizado"
echo "     └─ ✅ Para producción"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 DESARROLLO:"
echo ""
echo "  npm run dev               → Servidor de desarrollo"
echo "     └─ Hot reload automático"
echo "     └─ http://localhost:5173"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 COMPARACIÓN:"
echo ""
echo "  Tipo      Archivos  Tamaño    React    Editable  Portable"
echo "  ────────  ────────  ────────  ───────  ────────  ────────"
echo "  vanilla   4 files   ~28 KB    ❌ No    ✅ Sí     ⚠️  No*"
echo "  static    3 files   ~328 KB   ✅ Sí    ✅ Sí     ⚠️  No*"
echo "  inline    1 file    ~329 KB   ✅ Sí    ⚠️  No    ✅ Sí"
echo "  html      1 file    ~213 KB   ✅ Sí    ❌ No     ✅ Sí"
echo ""
echo "  * Requiere servidor web"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 EJEMPLOS DE USO:"
echo ""
echo "  # Desarrollo:"
echo "  npm run dev"
echo ""
echo "  # Build para editar HTML:"
echo "  npm run build:static"
echo "  # Luego edita: dist-static/index.html"
echo ""
echo "  # Build para compartir:"
echo "  npm run build:inline"
echo "  # Comparte: dist-inline/index.html"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 Más info: cat BUILD.md"
echo ""
